function tracks = initializeTracks()
    % create an empty array of tracks
    tracks = struct(...
        'id', {}, ...
        'bbox', {}, ...
        'kalmanFilter', {}, ...
        'age', {}, ...
        'totalVisibleCount', {}, ...
        'consecutiveInvisibleCount', {}, ...
        'initialCentroid', {}, ...
        'prevCentroid', {}, ...
        'curCentroid', {}, ...
        'speed', {}, ...
        'id2print', {});
end

